### ISSUE TITLE
Design a shared business card for MWC to hand out URLs

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/Engagement#1]
We can't hand out pretty collateral at MWC, so we're going to walk in with some handy business cards that point people to the MOI landing page.

This won't be a card for an individual, but for the program.  So, on the front, it should have at least:
- a heading/title: **Empowering the next billion citizens of the Web**
- mobileopportunity@mozilla.org
- webmaker.org/localweb

An idea @edrushka had was to communicate the multi-language nature of the project, so maybe use the backside to display some text in many languages?

/cc @sabrinang @edrushka @hpauljohnson @benrito @cecilepompei @amirad

**Comment by benrito** [comment]
+1 to @edrushka idea.

If it matches the color scheme and vibe of the site, something really simple with languages and a tag-line. Maybe "Webmaker: building a locally relevant web."

**Comment by HPaulJohnson** [comment]
- Prominent Mozilla Webmaker brand/logo
- Subhead: "Empowering the next billion citizens of the Web" or (Ben's) "Building a locally relevant web."
- webmaker.org/localweb for URL
- +1 to communicating multiple languages.

**Comment by edrushka** [comment]
I prefer "Empowering the next billion citizens of the Web" over "Building a locally relevant web." although fewer words might work better for design.

Do we want the shortlink or the full URL

Anyone have ideas on how to communicate multiple languages?

**Comment by HPaulJohnson** [comment]
for printed format I prefer to the full URL.

**Comment by davidascher** [comment]
Updated the initial comment with the decisions made so far.

**Comment by amirad** [comment]
Agree on prominence of Mozilla AND Webmaker logo. Need a logo they will recognize and tie back to the booth. 

The different language text on the backside is cool but I think a simple image might also suffice. Can even put the Mozilla Webmaker branding here.

**Comment by cassiemc** [comment]
@davidascher  What is the timeline on this? when do we need to send to the printer, and do we have a printer in mind?

**Comment by sabrinang** [comment]
redpen: https://redpen.io/p/vb6460daf4448b5e80

**Comment by davidascher** [comment]
Timeline is I'm leaving Friday am. Will be printed in Vancouver. We need to
send to printer asap.

**Comment by edrushka** [comment]
Who is making final decision on this? Can it be you, @davidascher?

**Comment by davidascher** [comment]
It can.  Let me know what decisions you need.

**Comment by edrushka** [comment]
Thanks! Ideally @sabrinang can do another version based on our feedback on the redpen, which you can sign off on tomorrow.

Also, @benrito @davidascher @HPaulJohnson -- just want to make sure you're aware Sabrina mocked up 3 different colours in the redpen. Click the "Next Design" button at the top to see the white and blue versions, and please indicate which you prefer. https://redpen.io/et595fc135b4e25320

**Comment by davidascher** [comment]
I prefer the white for writeability.

**Comment by HPaulJohnson** [comment]
+1 to white version so that you could write down personal contact info if necessary.

**Comment by edrushka** [comment]
Let's go with white. @sabrinang when can you have this finalized?

**Comment by sabrinang** [comment]
https://www.dropbox.com/s/umcy9qz5v4r5da7/mozilla-webmaker_mobile-opportunity-MWC-2015-march_business-card-for-print.pdf?dl=0

(exported with 0.125 in bleed)

**Comment by edrushka** [comment]
@sabrinang do you have the name of the printer, and who should best coordinate?

**Comment by edrushka** [comment]
Update:
@davidascher took cards to printers. Will be ready for pickup Wed Feb 25 and he will bring to MWC. Thanks everyone!

**Comment by amirad** [comment]
Thanks! Can't wait to flash those cards

**Comment by davidascher** [comment]
Picked up the cards today.  Thanks all.

![2015-02-25 11 02 48](https://cloud.githubusercontent.com/assets/51278/6378221/c0701d1c-bcde-11e4-9b34-6a9c12403a8f.jpg)

**Comment by benrito** [comment]
looking nice!

**Comment by cassiemc** [comment]
Awesome, looks great! Make sure to leave one / bring some back for Sabrina =)
