### ISSUE TITLE
Support Souktel roll out/phase 2

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#12]
Phase 2: give phones to kids to test the webmaker app
Support Souktel developing the phase 2 of their roll-out 

Dates: 8 weeks, start beginning of June

Driver: Cecile
Team: @laurareynal @amirad 
Interested: @benrito @thisandagain @secretrobotron

TO DO:
- [x] PRODUCT (research) cc @LauraReynal 
  Build Get research team to support Souktel in getting information to build Webmaker product
      - next version of webmaker? current version? cc @LauraReynal 
- [x] COMMUNICATION / FUNDRAISING
  How do we document the phase 2 (giving out phones and participants making more apps)
  - [x] COMMUNITY cc @amirad 
    How do we link this to the local community on the ground?
    How does this potentially become clubs?
    How do we involve the participants into the clubs?

**Comment by lauradereynal** [comment]
@cecilepompei Can you share what has been done so far? 
Im not aware of phase 1 :smile:

**Comment by benrito** [comment]
Phase 1 is documented here: https://blog.mozilla.org/m4d/2015/02/26/building-apps-for-social-change-in-east-africa-and-southeast-asia/

Video of Cambodia event: http://youtu.be/yyOLU0OeSkc http://youtu.be/yyOLU0OeSkc

Apps created at Cambodia event (using Appmaker):

https://overjoyed-church-178.webmak.es/app https://overjoyed-church-178.webmak.es/app Edukids (Winning App) an app that aims for educating kids whose age 4 to 6 year-old who can't read and write.
https://outstanding-plane-976.webmak.es/app https://outstanding-plane-976.webmak.es/app Drip Rate Counter is for for rural nurse who lack of knowledge on controlling the drip rate of baby. this app will provide them the accurate drip rate per minute.
https://profuse-chalk-269.webmak.es/app https://profuse-chalk-269.webmak.es/app Genno is for providing general knowledge on khmer culture to Cambodian Youth.
https://panoramic-cellar-66.webmak.es/app https://panoramic-cellar-66.webmak.es/app Guru is an app to test general knowledge.
https://silly-toad-614.webmak.es/app https://silly-toad-614.webmak.es/app AnnimalWorld an app that teach kids about animal with pictures and sounds.
https://zealous-elbow-864.webmak.es/app https://zealous-elbow-864.webmak.es/app KhmerFonts is the collection of free/paid khmer fonts.
https://nondescript-chalk-116.webmak.es/app https://nondescript-chalk-116.webmak.es/app Are You Fat? an app that tell if you are underweight, normal weight or overweight. it also provides the solution to those who underweight or overweight.
https://enchanting-word-62.webmak.es/app https://enchanting-word-62.webmak.es/app VoteMe helps providing the accurate vote.
https://wry-hour-735.webmak.es/app https://wry-hour-735.webmak.es/app MyTemple is introducing the top ten temples in Cambodia to more than two millions visitor who come to visit this country every year.
https://heavy-scale-590.webmak.es/app https://heavy-scale-590.webmak.es/app Traffic Question tests Cambodian Youth on the topic on Traffic Law.

**Comment by cecilepompei** [comment]
How dare you not read our blog !!!
:)
https://blog.mozilla.org/m4d/2015/02/26/building-apps-for-social-change-in-east-africa-and-southeast-asia/

On Tue, Mar 24, 2015 at 6:03 PM, Laura de Reynal notifications@github.com
wrote:

> @cecilepompei https://github.com/cecilepompei Can you share what has
> been done so far?
> Im not aware of phase 1 [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/Engagement/issues/12#issuecomment-85623656
> .

## 

Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by lauradereynal** [comment]
Thanks I had seen the blog post :)

**Comment by amirad** [comment]
What's the time frame for V2? Is this a good audience to develop some curriculum around the new app that we can maybe test with clubs?

**Comment by benrito** [comment]
@amirad time frame is as soon as we can make it work!

Do you want to listen in on call tomorrow? 10:30ET

**Comment by cecilepompei** [comment]
@amirad could you clarify please? I am preparing for building this phase 2 and would love all info to make sure i design it right to help

**Comment by lauradereynal** [comment]
Here is a draft for the research / product feedback part of this project

_Countries_: Rwanda - Cambodia 
_Phase 2_: People are receiving a phone. They will create content with Webmaker App. 
_Objective_: Understand how youth perceive the Webmaker app after a long time spent using it. 

_Questions_ cc @secretrobotron @thisandagain 
- How would people qualify Webmaker / How do they see it ?
- Do they like using it ? 
- Is it fun ? 
- Do they learn anything while using it ?
- Does the product enable them to do what they want ? 
- How could we improve it ? What did they wish it could do but it does not do today?
- What did they create ? 
- What did people wish to learn ? 

_Methods_ 
- Souktel's local partner will conduct interviews with a selected number of youth
- They will fill in the answers in a google doc spreadsheet that we can access
- Ideally they would do an interview before they start using the produc, and a second one after they used it for a while (Time to determine)
- Debrief call with the local partner / Souktel / Mozilla

TO DO 
- [x] Laura to create the spreadsheet template for the interviews and share it with team for review 
- [x] @cecilepompei to see if this fits Souktel and partners needs 
- [ ] @cecilepompei will follow up with the project, and I will help when needed

**Comment by lauradereynal** [comment]
Need : Dates

**Comment by amirad** [comment]
@benrito want to send me dial-info. Can silently listen in if you think that would help. 
@cecilepompei I am hearing that we will eventually want a club module that is focused around the Webmaker App which means we will need to start building and testing activities with the product in the real world while teaching web literacy.

**Comment by cecilepompei** [comment]
Notes from the call here:
https://foundation.etherpad.mozilla.org/souktel

**Comment by cecilepompei** [comment]
@LauraReynal - we need to have a work session on preparing this, following the call with Souktel.

Here are the notes that summarize how we collect information from the participants that will receive mobile phones:

Questions to address:
- How long is the study piece of this?
  8 weeks
- How do we document?
  - [x]   intro interview 
    
    then youth driven collection
    
    ask them to take photos / videos
    
    write a short guide or template for them?
    
    selfie -- where we're going
  - [x]  exit interview
    
    ask questions
    
    download everything off the SD card
  - [x] how to synthesize?
    
       write series of blog posts >  Souktel? Mozilla?
  - [x] How do we get great feedback from the app?
    
    provide questions for intro / exit interview
    
    create a form to track what people are saying (laura/cecile)
- how do we incentivise the participants to come back and let us download what they have created?
  
  "we want to share your story"
  
  if you complete the activity, you'll get to keep the phone
  
  Mozilla club - show participants they could be part of mozilla community
  
  implication: there are more career development opportunities
  
  get involved in testing stuff
  
  join and work on an international software project
  
  get credentials (eventually)

**Comment by cecilepompei** [comment]
Prepared an action plan with Souktel - notes here https://foundation.etherpad.mozilla.org/souktel

What do we need to solve?

```
     1) Phones - Price quotes to check whether cheaper to buy them locally and invoice Mofo or ship them from the US. Hard to ship phone, only 30 available. @Nicola

2) Kick off date? depends on phones. different dates for Rwanda and Cambodia @nicola

3) step 1: Intro interview 
```

When participants come and pick up forms there will be an intro interview - who writes the intro interview
Intro interview will be done by Souktel partner @Nicola
in case partner does not have the time, can do a google forum where ppants answer the questions online when they pick up the phone
-  Technics to show pictures of ppants in their communities when they present/introduce their apps @nicola
-  How to send the pictures back (email Nicola) @nicola
-  guidelines for the pictures @nicola
  -   Intro interview prepare on google doc @Cecile, @LauraReynal (expectations, background, etc) 
  -   What are the guidelines for process and monitoring @nicola
    
    4) Step 2: exit interviews

after 2 months, participants come back to partner in country or fill another form online

```
-  Prepare exit interview form @Cecile, @LauraReynal 

-   Collect all new apps that are made @Nicola

- Collect all pictures made and gather in one place @Nicola

-   how do we leverage these participants into a potential community or club? @amirad input? - how do we gather them into a group that meets regularly . Some participants have started to teach already digital classes

 - How do we support them for the future if needs be? @cecile

 - Do we need communication on step 2 ? is Laura making a report on a few participants? @cecile, @LauraReynal 

5) Create a google folder to exchange documents @cecile
```

**Comment by lauradereynal** [comment]
cc / @APLsmith

**Comment by lauradereynal** [comment]
Hey @cecilepompei I drafted in details the research brief that you can find here 
https://docs.google.com/document/d/1E7KhGLGGvHri_LQh2Q5_p6-Xe6JBR9Y_nPgEzVgQWZ8/edit?usp=sharing

It definitely needs a second pass - but its a good start to show @nicola and gather a first round of input. 

However, I realised while doing this that I lack a lot of information about Souktel. 
Could you create a 1 pager on the google doc folder here https://drive.google.com/a/mozilla.com/folderview?id=0B0X05aIHuAbedGFwRUotV2Y4Vms&usp=sharing
With the following information : 
- How many "students" ?
- How many trainers ?
- What is the program about ? 
- In which country ? 
- who are the stakeholders ? For Now I know Souktel + an implementation partner + Mofo ? 

Depending on the answer on these questions I will adjust the methods. For example if there are less than 10 "trainers" I will prefer to do skype interviews rather than a Google form.

**Comment by lauradereynal** [comment]
Also, I am confused about your notes in the previous ticket " tecnics to show pictures of participants in their community" Could you expand please ?

**Comment by cecilepompei** [comment]
@LauraReynal I cannot access your folder, and we had created a team folder for SOuktel phase 2
here: https://docs.google.com/a/mozilla.com/document/d/1KTZE17e-ZDnGkcr1NSx3nTsokAwpug9mMTSwagAQ4Fk/edit?usp=sharing
- in this Souktel folder, I have added the information you need under "Souktel details" 
- pictures: its a Nicola action item. She will write little guidelines for people on how to take good pictures to document this programme
- research: will get it checked by nicola and I

**Comment by lauradereynal** [comment]
@cecilepompei here is the folder (with only one doc for now)
https://drive.google.com/open?id=0B0X05aIHuAbedGFwRUotV2Y4Vms&authuser=0
Here is the document Souktel Research Brief 
https://docs.google.com/document/d/1E7KhGLGGvHri_LQh2Q5_p6-Xe6JBR9Y_nPgEzVgQWZ8/edit?usp=sharing

**Comment by APLSmith** [comment]
@laurareynal Have added a few comments and questions on the Google Doc

**Comment by cecilepompei** [comment]
@LauraReynal - now that we have the answers, do you need anything to help you draft the intro interview (And exit interview, but these are coming 8 weeks after)

@amirad - we have a group of young participants in an app maker intro day in Cambodia and Rwanda. They are now all given phones with webmaker on it and encouraged to create more apps and show them to their community.
How do we try and involve them in Mozilla communities? how could we help if they want to become club leaders or more?

**Comment by lauradereynal** [comment]
@cecilepompei the intro and exit interviews are already drafted. We still need to figure out who will conduct them and how 

When do you want this project to start ?

**Comment by cecilepompei** [comment]
super! I was making sure the info does not change what you had drafted
before.
This should start when we have the phones in the hands of the participants
which is from 1 to 3 weeks Id say

On Mon, Apr 13, 2015 at 3:16 PM, Laura de Reynal notifications@github.com
wrote:

> @cecilepompei https://github.com/cecilepompei the intro and exit
> interviews are already drafted. We still need to figure out who will
> conduct them and how
> 
> When do you want this project to start ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/Engagement/issues/12#issuecomment-92347851
> .

## 

Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by amirad** [comment]
Some ideas on how to involve those in Cambodia/Rwanda:
•We're hiring a Curriculum Director who can test our new mobile curriculum with them. Just a thought but can look more into this once that person is hired. 
•They might make for good people to join our club testers, club launchers or even testing @LauraHilliger how to teach like mozilla modules
•We assign them a regional coordinator that helps them build out clubs in their areas

**Comment by cecilepompei** [comment]
Super @amirad , thanks for the input
Probably option 1 and 3 - so far, the people receiving the phones are going to be helping us testing webmaker, so hard to test everything on them if it makes sense.

maybe on our side, we collect feedback as well and see what kind of support they need, link them with the local community?

**Comment by amirad** [comment]
Sure. I think building in some sort of training or info on how to start a club and registering those that want to be more involved/start a club is a good start. We can take that group and assign them RC's and use them to share continuous club material.

**Comment by cecilepompei** [comment]
do we have this info on starting a club?
i will make sure we add to the exit interview whether they would want to
teach digital literacy, how often, etc @laurareynal

On Mon, Apr 13, 2015 at 10:55 PM, Amira notifications@github.com wrote:

> Sure. I think building in some sort of training or info on how to start a
> club and registering those that want to be more involved/start a club is a
> good start. We can take that group and assign them RC's and use them to
> share continuous club material.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/Engagement/issues/12#issuecomment-92495378
> .

## 

Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by amirad** [comment]
Info will be on teach.mozilla.org when it launches next heartbeat
