### ISSUE TITLE
World Bank S4YE RFP: Agreement on scope of work

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/Engagement#13]
Driver: Ben
Team: @anmechung @metaphorista @irisbond
Interested: @cecilepompei @msurman

Tracking: https://docs.google.com/document/d/1RUE9U-ROXqfjSfhRskE6nN1mwKruBeKo1uHpIPiiARI/edit

**Comment by benrito** [comment]
Parking lot:

https://docs.google.com/a/mozillafoundation.org/document/d/1ibTA69IHRhmLRR7StAnF5vjd9cpFCW8AROZAS_jqpDE/edit

https://foundation.etherpad.mozilla.org/sye

**Comment by cecilepompei** [comment]
Have field partner for south africa as well (great social entreprise, focus youth employment, very well known - check RLABS - could do testing with them too)

**Comment by benrito** [comment]
@anmechung's new document https://docs.google.com/a/mozillafoundation.org/document/d/1mTVBlb6V_nxDyGPClAvhxmLHLyVUdvsEK9GEVjReMMo/edit

**Comment by anmechung** [comment]
Proposal submitted to World Bank on April 6, 2015.
