### ISSUE TITLE
Gates Foundation FSP: agree on scope of work

### ISSUE THREAD

**Issue by benrito** [MozillaFoundation/Engagement#14]
Driver: Ben
Team: @thisandagain @LauraReynal
Interested: @cecilepompei @msurman

Tracking here: https://foundation.etherpad.mozilla.org/gates-proposal?

**Comment by benrito** [comment]
World Bank proposal taking priority this week: https://github.com/MozillaFoundation/Engagement/issues/13

Will clean up the scope of work ASAP so we can advance to the proposal writing phase.

Any thoughts or comments in the meantime appreciated.

Eyes on April 8th when y'all are headed to SF. We ought to be well done by then.

**Comment by thisandagain** [comment]
:+1: Sounds good. Will find some time to drop some additional thoughts from latest product work early next week. Much appreciated.
