### ISSUE TITLE
Sign MoU Dnet

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#18]
Driver: Cecile
Team: @benrito 
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1137797
- [x] Changes to the MoU (Dnet, dates) @cecile
  - [x]  Questions to ask internally @cecile
    - Dnet cannot send original of their receipts since they have to give that to their audit team
    - Need to collect Dnet payment details
  - [ ] Send Dnet payment (bank) detail @Ropum
  - [x] Receipts original question @cecile
  - [x] Can Dnet mention Mozilla Foundation as a partner? what are the branding guidelines? @cecile @benrito 
  - [x] what is the travel policy for Dnet? @cecile @benrito 

Send and sign

**Comment by cecilepompei** [comment]
@benrito filling on bugzilla - Who can provide me the information about the branding guidelines?

**Comment by benrito** [comment]
I’m not sure we have standard guidelines for partnership representation. As long as they’re not doing anything unusual with the trademark, we would be happy, and indeed proud, for Dnet to recognize us as a partner/client with a logo on their site.

Visually speaking, we do have a standard style guide: https://www.mozilla.org/en-US/styleguide

Beyond the logo—as long as we are given an opportunity to review anything (blog post, case study etc) before it gets published, we’ll be fine.

Cheers!
Ben

**Comment by cecilepompei** [comment]
we have added legal input on the MoU and Angela will sign this anytime now
