### ISSUE TITLE
Prepare the Bangladesh Master Plan

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#23]
Driver: @Cecile
Team: @APLSmith @Laurareynal @benrito 
Interested: @amirad @davidascher @secretrobotron @thisandagain 

I have spent this morning with Alex (GSMA) to draft our master-action-plan-too-big-to-be-a-bug!

It is on this excel sheet Bangladesh-Master-Plan

To make the excel plan clear:
    - The objectives are the key strategic objectives to this project. It needs to define a measurable goal (yes Ben, I used your Bangladesh overall document)
    - The key to the map is the dates so we all agree
    - the tab "project plan" is the master document that you want to have a look at (though it is a lot of information)
We have listed all action items one by one, with a few indications, a due date, people involved, and a timeline on the right. Pretty straightforward.

Note: On the weekly research call, I will filter by due dates and make sure that everyone is on track

Next steps:
- have a look and see if we have forgotten something
- put your name on a few action if needed
- where you put your name, please fill the "measure of success" cell for each action
- Lets review next monday on our weekly call - we need to have the dates in as well, as much as we can, to start moving forward
- I have added you to a folder on google drive: https://drive.google.com/drive/u/1/#folders/0Bwnbtdj7aspSTUJ0Wl9kYjJDSm8/0Bwnbtdj7aspSZk1vTnhzd3g4Snc
- Team, please have a look at the tab "questions" and start thinking about answers for the Monday call

**Comment by lauradereynal** [comment]
thanks @cecilepompei a few points : 
- How do you see the difference between a control group and a treatment group ? ( Dnet ) 
- I thought we agreed we would minimize the number of MNOS in order to minimize the workload and intermediairies in this project ? 
- I had a look at the questions tab, and so far I can answer line 12 with this plan https://drive.google.com/open?id=1hnpXwboPWv_VLa_NiKHYDnWyIB9IjEc89adoKgOuvPY&authuser=0 and this planning https://drive.google.com/open?id=1V9t2RUK51lnk30I00nCg2-ctxyHDMUBUtFrUAaoDfis&authuser=0

**Comment by cecilepompei** [comment]
- Control groups get the phone without any training and treatment groups are the ones that get phone + some training on digital literacy and webmaker -- right @APLSmith?
- I did not know we agreed to minimize the number of MNO (@Benrito?) - but I think the workshop can have everyone and we can gauge who wants to go further. I suspect not all MNO
- planning yes for research but what we thought with @APLSmith is that the research will be two fold:
  1) research of Dnet (they can do that themselves but would be great to have you a week on this for example)
  2) research with more groups from the MNO - this can start only after the workshop with them from my understanding so I suspect... not before July! (if things happen fast, which we all hope)

**Comment by lauradereynal** [comment]
Thanks @cecilepompei 
I thought 2) was what we were doing in June. why Is it July ?

**Comment by cecilepompei** [comment]
The workshop happens 10th lets say of june. The time to follow up with them
and make it happen - June research with the MNO seems impossible . But we
can discuss!
