### ISSUE TITLE
Decide who will show Webmaker in Bangladesh

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#24]
Driver: Cecile
reference: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1gcjul0xAQQZoVXsX9fRUoKMwNPt9swYrQSMd1bVnxyE/edit#gid=1985808196
Team: @amirad @laurareynal
Interested: @benrito @APLSmith

For the Bangladesh research on Webmaker starting in May (to prove whether giving phones to Youth with webmaker on it and a bit of training supports local content creation)

1) @Laurareynal, we need someone in your team that can train someone in Bangladesh on the new webmaker tool (or the current version) to the treatment group of the research @thisandagain 

and 2) @amirad , Could we use a local Mozilian for an hour or two in Dhaka to show 10-30 people how to use the webmaker tool?

thanks!

**Comment by amirad** [comment]
Show them how to use the **new** webmaker tool? 

Salman, Tanha, Maliha have all taught at events while using past Webmaker tools and we can reach out to them. Salman has been very actively engaged with Webmaker over the past couple years, I might start with him. Maybe @laurareynal has a preference?

**Comment by lauradereynal** [comment]
Happy to do a prep call with both salman and Zak
Will reach out to them

**Comment by cecilepompei** [comment]
Super, thank you to you both
The timeline is for probably the Mozilian to do this training first week of May - would that work for you?

**Comment by cecilepompei** [comment]
cc @benrito 
Ben is recommending Zak
Are we good to do that?

**Comment by lauradereynal** [comment]
The first week of may is really soon 

! I just finished talking with Zak, he is on-board but we have lots of work to do for this training. All what we teach will influence the research outcome. 
Im thinking we want to know if basic understanding of the internet and digital literacy will influence usage of smartphone. We can show webmaker, but I think the literacy part will be the most interesting. 
Im talking again with him next week. and will copy him in the emails

**Comment by benrito** [comment]
Awesome, thank you for update. Seems we might want to lean in a bit and view this as a curriculum generation task (and running the training per this curriculum as the last step). Resources may be available for this.

Alex and Cecile and I are working on strategy today, and this fits in very nicely with where we’re going. Documentation coming soon but perhaps 15 minute call would be well spent.

**Comment by lauradereynal** [comment]
I agree with 15 mins call
Can you do right now ? On my way to interviews - after that its back to
back
