### ISSUE TITLE
Sourcing phones for Bangladesh

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#25]
Driver: Cecile
reference: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1gcjul0xAQQZoVXsX9fRUoKMwNPt9swYrQSMd1bVnxyE/edit#gid=1985808196
Team: @benrito 
Interested: @APLSmith @thisandagain @laurareynal

@benrito - we need to support Dnet into sourcing phones for the research, starting beginning of May
- what kind of phones shall they get?
- locally or shall we send the phones to them?
- Does dnet buy the phones and send us bills?

**Comment by benrito** [comment]
Android 4.2 — preferred protocol is for them to get a quote from local vendor, we OK, they buy, and they invoice us. But we can be flexible.

We should want cheap, low-end phones that are fairly representative of what’s popular in the market.

Cheers!
Ben

**Comment by lauradereynal** [comment]
ALSO, can  you guys plan for data plans ? 
We need to give money to those people if we expect them to use mobile data

**Comment by benrito** [comment]
Yes!

**Comment by cecilepompei** [comment]
Are we happy with this?
- ```
       Brand: Symphony (Symphony is the most popular and representative brand in Bangladesh in perspective of user)
  ```
- ```
       Model: Xplorer W69Q
  ```
- ```
       Operating System: Android 4.4.2 Kit Kat (most available in Bangladesh now)
  ```
- ```
       Processor: 1.3 GHz Quad Core
  ```
- ```
       RAM: 1 GB
  ```
- ```
       ROM: 4 GB
  ```
- ```
       Display: 4”
  ```

**Comment by APLSmith** [comment]
Looks good to me @cecilepompei 

Price is ~75 USD (~5840 taka) according to the internet.

**Comment by thisandagain** [comment]
:+1: @cecilepompei 

Can we get two test devices ASAP? One shipped to the Portland office and one to the Toronto office should be sufficient.

/cc @k88hudson

**Comment by benrito** [comment]
cc @thisandagain

**Comment by benrito** [comment]
If we can order offline, we can use a Mozilla card

**Comment by cecilepompei** [comment]
So we had to move since the research starts 16th May - Dnet is purchasing these phones
shall I still send 2 to the US?
(sent an email to you Andrew on process around this)

**Comment by benrito** [comment]
yes—

can we order the 2 directly from an e-retailer, rather than having dnet do it?

**Comment by cecilepompei** [comment]
There is no online shops in BD to get this directly, and DHL said they could not ship this to the US (customs forbid batteries)
I am working on alternative solutions right now
