### ISSUE TITLE
Souktel - how do we communicate around this project?

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#28]
Driver: Cecile
Team: @laurareynal @benrito @amirad 

Hi team,
Based on this phase 2 where participants receive phones with Webmaker on it, 
how do we want to communicate around this?

I think it is important enough to dedicate some effort and the participants have been very involved in the project and therefore it is a great project to illustrate!

Options:
- Laura goes to Cambodia or Rwanda (both seem a bit much) for a week during exit interviews and document a few participants and build a documentary like
- We will have pictures that the participants will have made (based on a few guidelines) with their communities
- the local Mozilians that will help us with intro / exit interviews can help as well taking a few pictures? 

Your thoughts on this and added to this?

**Comment by lauradereynal** [comment]
Do we know potential dates and budget for coms ? It would help inform a decision.
