### ISSUE TITLE
Prepare the Souktel phase 2 - research SOW

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#30]
Phase 2 - CASE STUDY “Mobile content creation by first mobile phone users”

Research Objective
Souktel and Mozilla Foundation will together conduct qualitative research to show that local content creation can be done on mobile and be spread virally (because it is so easy to share).
This research will help Mozilla Foundation to understand how to virally spread a mobile local content creation tool. to measure the impact of our Webmaker pilot and inform its next steps.

Project Manager: @cecile
Driver: @laurareynal (research side)
Team: @benrito @APLSmith @thisandagain @secretrobotron 

We need to agree on the research scope from here: https://docs.google.com/document/d/1E7KhGLGGvHri_LQh2Q5_p6-Xe6JBR9Y_nPgEzVgQWZ8/edit# -- please review and comment (p1,2)

Call for Alex / Ben / Laura / Cecile to talk about this on Friday 22.05

**Comment by lauradereynal** [comment]
@cecilepompei
Can you add a tentative timeline please?

**Comment by cecilepompei** [comment]
it is written in the document (your research brief) - added a lot of
details:

proposed timeline:
- mid june / mid august

On Thu, May 21, 2015 at 6:35 PM, Laura de Reynal notifications@github.com
wrote:

> @cecilepompei
> Can you add a tentative timeline please?
> 
> Sent from a mobile device.
> On May 21, 2015 4:21 PM, "cecilepompei" notifications@github.com wrote:
> 
> > Phase 2 - CASE STUDY “Mobile content creation by first mobile phone
> > users”
> > 
> > Research Objective
> > Souktel and Mozilla Foundation will together conduct qualitative research
> > to show that local content creation can be done on mobile and be spread
> > virally (because it is so easy to share).
> > This research will help Mozilla Foundation to understand how to virally
> > spread a mobile local content creation tool. to measure the impact of our
> > Webmaker pilot and inform its next steps.
> > 
> > Project Manager: @cecile https://github.com/cecile
> > Driver: @laurareynal https://github.com/laurareynal (research side)
> > Team: @benrito https://github.com/benrito @APLSmith
> > https://github.com/APLSmith @thisandagain
> > https://github.com/thisandagain @secretrobotron
> > https://github.com/secretrobotron
> > 
> > We need to agree on the research scope from here:
> > 
> > https://docs.google.com/document/d/1E7KhGLGGvHri_LQh2Q5_p6-Xe6JBR9Y_nPgEzVgQWZ8/edit#
> > -- please review and comment (p1,2)
> > 
> > Call for Alex / Ben / Laura / Cecile to talk about this on Friday 22.05
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MozillaFoundation/Engagement/issues/30.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/Engagement/issues/30#issuecomment-104366613
> .

## 

Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115
