### ISSUE TITLE
Urgent, P1: cat measurement needed

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Engagement#6]
:woman: :pensive: :question:
:cat: :straight_ruler: :banana: :interrobang:
@secretrobotron

**Comment by secretrobotron** [comment]
Some questions before I sprint on this:
- do we have the right measuring tools for this? can file a service now request if not. budget?
- what units? centimeters? bananas?
- what format do you need the results in? can make a new site to publish, but should go through design review first

**Comment by edrushka** [comment]
Thanks for these questions, @secretrobotron. Appreciate you gathering evidence to support your claim that your cat is, indeed, huge.

Non-organic bananas should be used as the measuring device as they are more consistent in size. As budget for this is $0, suggest you wear dark glasses, a fedora and an overcoat to disguise your identity, and steal from the TOR fruit basket. If caught, deny everything. Might want to link timing of banana heist for when JP is in the office - as a fellow cat scientist, he'll likely see the importance of this ticket and will cover for you.

Measurement unit is bananas, skin on. No one wants to eat a banana with cat hair on it.

Mobile-optimized site with simple nav and links to [related content](http://www.buzzfeed.com/petsami/15-cats-wearing-fruit-helmets-5ojq) would be ideal, but MVP is photo documentation.

**Comment by secretrobotron** [comment]
cc'ing @jdotpz to check with his schedule

**Comment by jdotpz** [comment]
One observes that the measurement of cats using bananas is a fundamentally flawed methodology.  

https://www.youtube.com/watch?v=VJjReLsq5DM

**Comment by edrushka** [comment]
@jdotpz It seems you are correct. Initial testing with Shreddy resulted in [loss of banana](https://www.dropbox.com/s/46hiw2imkud1y6a/banana.jpeg?dl=0)

**Comment by edrushka** [comment]
I guess Ben is more of a dog person.

**Comment by secretrobotron** [comment]
![ev6qmqhyggykzjmplopk0xs_4ynhhgej4ox0dlb40re](https://cloud.githubusercontent.com/assets/403231/7872883/bebb6890-0569-11e5-9caf-a0b86c8cf2aa.jpeg)

**Comment by edrushka** [comment]
![benlovescats](https://cloud.githubusercontent.com/assets/4515662/7873253/c0dab44c-0554-11e5-921d-31f44be95074.jpg)

I'm just going to leave this here.

**Comment by benrito** [comment]
![benfight](https://cloud.githubusercontent.com/assets/541325/7878632/e192710e-05e8-11e5-86b3-d70647c7fc0f.png)
