### ISSUE TITLE
Orange Partnership - Finish Orange Klif proposal

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#7]
Driver: Cecile
Team: @amirad @benrito 
- [x] Touch base with the French team
- [x] Write various cooperation options (internal)
- [x] Add figures and how much it would be to roll out a cooperation on digital literacy options @amirad 
- [x] email @mobileopportunity for info

**Comment by cecilepompei** [comment]
Re did the structure and think it is more straightforward now -- to put figures on this, I sadly (sadly because means more work) to get Amira's numbers
Ready when you are Amira! happy to do it over skype in 15 min if it makes it easier for you!

**Comment by amirad** [comment]
I'm in the doc right now but have questions over the numbers (and hesitancy putting numbers!) to a lot of those community programs. Would love to talk it through first. 

cc: @thornet should have a look at the doc https://docs.google.com/a/mozilla.com/document/d/1yphkofBq7jMAdqBD3QVkCkK1vfsLPOBdijHSKPQwIG0/edit?usp=sharing
