### ISSUE TITLE
Orange partnership - Write a proposal for Orange Foundation (MVP)

### ISSUE THREAD

**Issue by cecilepompei** [MozillaFoundation/Engagement#8]
- [x] Write proposal to submit to Orange (Minimum viable partnership):
        - proposal for job creation, digital literacy classes, pilot in 1/2 incubators in Africa
- [x] Ask to be introduced to selected national foundation team
- [ ] pitch to local incubators in Africa
- [ ] Feasibility studies of how many job created through digital literacy course 

cc @benrito

**Comment by benrito** [comment]
Re: job creation—the Friday call with David Humphrey will help a lot!

Would be worthwhile to think about how we could pilot a program with Muzinda based on a unified model.

**Comment by cecilepompei** [comment]
Can we re schedule the call @benrito ?
